services:
  - docker

script:

    # Get images
  - docker pull ghdl/ghdl:buster-gcc-8.3.0
  - docker pull cdelledonne/msp430-gcc

    # Testing installations
  - docker run -t ghdl/ghdl:buster-gcc-8.3.0 ghdl --version
  - docker run -t cdelledonne/msp430-gcc msp430-elf-gcc -v

    # Run SW check (check if all example projects + bootloader are compiling)
  - >
    docker run -t -v `pwd`:/mnt/data cdelledonne/msp430-gcc
    /bin/bash -c  "chmod u+x /mnt/data/travis_ci/sw_check.sh; /mnt/data/travis_ci/sw_check.sh"

    # Run HW check
  - >
    docker run -t -v `pwd`:/mnt/data ghdl/ghdl:buster-gcc-8.3.0
    /bin/bash -c  "chmod u+x /mnt/data/travis_ci/hw_check.sh; /mnt/data/travis_ci/hw_check.sh"

notifications:
  email:
    on_success: never
    on_failure: always
